import 'dart:io' show Platform;
import 'dart:typed_data';

import 'package:audioplayers/audioplayers.dart';
import 'package:file_picker/file_picker.dart';
import 'package:flutter/foundation.dart' show compute;
import 'package:flutter/material.dart';
import 'package:gaimon/gaimon.dart';
import 'package:haptify/haptify.dart';

import 'generated/explosion_01_haptic.dart';
import 'generated/gong_01_haptic.dart';
import 'generated/hit_01_haptic.dart';
import 'generated/spring_03_haptic.dart';

void main() => runApp(const HaptifyDemoApp());

/// A bundled sound with haptics pregenerated by `haptify convert` at build
/// time (see `lib/generated/`).
class Sample {
  const Sample({
    required this.name,
    required this.asset,
    required this.ahap,
    required this.timings,
    required this.amplitudes,
  });

  final String name;
  final String asset;
  final String ahap;
  final List<int> timings;
  final List<int> amplitudes;
}

const List<Sample> samples = [
  Sample(
    name: 'Hit',
    asset: 'audio/hit_01.mp3',
    ahap: hit01Ahap,
    timings: hit01Timings,
    amplitudes: hit01Amplitudes,
  ),
  Sample(
    name: 'Explosion',
    asset: 'audio/explosion_01.mp3',
    ahap: explosion01Ahap,
    timings: explosion01Timings,
    amplitudes: explosion01Amplitudes,
  ),
  Sample(
    name: 'Gong',
    asset: 'audio/gong_01.mp3',
    ahap: gong01Ahap,
    timings: gong01Timings,
    amplitudes: gong01Amplitudes,
  ),
  Sample(
    name: 'Spring',
    asset: 'audio/spring_03.mp3',
    ahap: spring03Ahap,
    timings: spring03Timings,
    amplitudes: spring03Amplitudes,
  ),
];

/// Plays a haptic pattern with gaimon: AHAP on iOS, the haptify-rendered
/// waveform on Android.
void playHaptic({
  required String ahap,
  required List<int> timings,
  required List<int> amplitudes,
}) {
  if (Platform.isIOS) {
    Gaimon.patternFromData(ahap);
  } else {
    Gaimon.patternFromWaveForm(timings, amplitudes, false);
  }
}

/// The outcome of converting uploaded audio, shaped to cross the isolate
/// boundary as plain data.
class ConversionResult {
  const ConversionResult({
    required this.durationMs,
    required this.transients,
    required this.continuous,
    required this.ahap,
    required this.timings,
    required this.amplitudes,
    required this.warnings,
  });

  final int durationMs;
  final int transients;
  final int continuous;
  final String ahap;
  final List<int> timings;
  final List<int> amplitudes;
  final List<String> warnings;
}

/// Runs haptify's full runtime pipeline off the UI thread.
ConversionResult convertUploadedBytes(Uint8List bytes) {
  final pattern = const AudioAnalyzer().analyzeBytes(bytes);
  final waveform = pattern.toWaveform();
  return ConversionResult(
    durationMs: pattern.totalDuration.inMilliseconds,
    transients: pattern.events.whereType<TransientEvent>().length,
    continuous: pattern.events.whereType<ContinuousEvent>().length,
    ahap: pattern.toAhap(),
    timings: waveform.timings,
    amplitudes: waveform.amplitudes,
    warnings: [for (final w in waveform.warnings) w.message],
  );
}

class HaptifyDemoApp extends StatelessWidget {
  const HaptifyDemoApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'haptify demo',
      theme: ThemeData(colorSchemeSeed: Colors.deepOrange),
      home: const DemoPage(),
    );
  }
}

class DemoPage extends StatefulWidget {
  const DemoPage({super.key});

  @override
  State<DemoPage> createState() => _DemoPageState();
}

class _DemoPageState extends State<DemoPage> {
  final AudioPlayer _player = AudioPlayer();

  bool _converting = false;
  String? _uploadName;
  ConversionResult? _result;
  String? _error;

  @override
  void dispose() {
    _player.dispose();
    super.dispose();
  }

  Future<void> _playSample(Sample sample) async {
    // Start audio and haptics together.
    await _player.stop();
    _player.play(AssetSource(sample.asset));
    playHaptic(
      ahap: sample.ahap,
      timings: sample.timings,
      amplitudes: sample.amplitudes,
    );
  }

  Future<void> _pickAndConvert() async {
    final picked = await FilePicker.platform.pickFiles(
      type: FileType.custom,
      allowedExtensions: const ['mp3', 'wav'],
      withData: true,
    );
    final file = picked?.files.singleOrNull;
    final bytes = file?.bytes;
    if (file == null || bytes == null) return;

    setState(() {
      _converting = true;
      _uploadName = file.name;
      _result = null;
      _error = null;
    });
    try {
      final result = await compute(convertUploadedBytes, bytes);
      setState(() => _result = result);
    } on AudioDecodeException catch (e) {
      setState(() => _error = e.message);
    } finally {
      setState(() => _converting = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('haptify demo')),
      body: ListView(
        padding: const EdgeInsets.all(16),
        children: [
          const _SupportBanner(),
          const _SectionHeader(
            'Bundled samples',
            'CC0 sounds converted at build time with `haptify convert`. '
                'Tap to hear the sound and feel its haptic together.',
          ),
          for (final sample in samples)
            Card(
              child: ListTile(
                leading: const Icon(Icons.vibration),
                title: Text(sample.name),
                subtitle: Text('${sample.timings.length} waveform segments'),
                trailing: const Icon(Icons.play_arrow),
                onTap: () => _playSample(sample),
              ),
            ),
          const SizedBox(height: 24),
          const _SectionHeader(
            'Convert your own',
            'Pick a WAV or MP3 from your device; haptify analyzes the bytes '
                'at runtime — no files written, no ffmpeg.',
          ),
          FilledButton.icon(
            onPressed: _converting ? null : _pickAndConvert,
            icon: _converting
                ? const SizedBox.square(
                    dimension: 18,
                    child: CircularProgressIndicator(strokeWidth: 2),
                  )
                : const Icon(Icons.upload_file),
            label: Text(_converting ? 'Converting…' : 'Pick a WAV or MP3'),
          ),
          if (_error != null)
            Card(
              color: Theme.of(context).colorScheme.errorContainer,
              child: Padding(
                padding: const EdgeInsets.all(16),
                child: Text('Could not convert $_uploadName: $_error'),
              ),
            ),
          if (_result case final result?)
            _ResultCard(
              name: _uploadName ?? 'upload',
              result: result,
              onPlay: () => playHaptic(
                ahap: result.ahap,
                timings: result.timings,
                amplitudes: result.amplitudes,
              ),
            ),
        ],
      ),
    );
  }
}

class _SupportBanner extends StatelessWidget {
  const _SupportBanner();

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<bool>(
      future: Gaimon.canSupportsHaptic,
      builder: (context, snapshot) {
        if (snapshot.data ?? true) return const SizedBox.shrink();
        return Card(
          color: Theme.of(context).colorScheme.errorContainer,
          child: const Padding(
            padding: EdgeInsets.all(16),
            child: Text(
              'This device reports no haptic support — simulators and some '
              'emulators cannot vibrate. Run on a real phone to feel the '
              'patterns.',
            ),
          ),
        );
      },
    );
  }
}

class _SectionHeader extends StatelessWidget {
  const _SectionHeader(this.title, this.body);

  final String title;
  final String body;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Padding(
      padding: const EdgeInsets.only(bottom: 12, top: 8),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(title, style: theme.textTheme.titleLarge),
          const SizedBox(height: 4),
          Text(body, style: theme.textTheme.bodySmall),
        ],
      ),
    );
  }
}

class _ResultCard extends StatelessWidget {
  const _ResultCard({
    required this.name,
    required this.result,
    required this.onPlay,
  });

  final String name;
  final ConversionResult result;
  final VoidCallback onPlay;

  @override
  Widget build(BuildContext context) {
    return Card(
      margin: const EdgeInsets.only(top: 12),
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(name, style: Theme.of(context).textTheme.titleMedium),
            const SizedBox(height: 8),
            Text(
              '${result.durationMs} ms of haptics · '
              '${result.transients} transients · '
              '${result.continuous} continuous · '
              '${result.timings.length} waveform segments',
            ),
            for (final warning in result.warnings)
              Padding(
                padding: const EdgeInsets.only(top: 4),
                child: Text(
                  warning,
                  style: Theme.of(context).textTheme.bodySmall,
                ),
              ),
            const SizedBox(height: 12),
            FilledButton.tonalIcon(
              onPressed: onPlay,
              icon: const Icon(Icons.vibration),
              label: const Text('Play haptic'),
            ),
          ],
        ),
      ),
    );
  }
}
