import 'package:path/path.dart' as p;

import '../encoders/waveform/android_waveform.dart';

/// Derives a lowerCamelCase Dart identifier prefix from a file name, e.g.
/// `heavy-hit_01.wav` → `heavyHit01`.
String dartIdentifierFor(String filePath) {
  final base = p.basenameWithoutExtension(filePath);
  final words = base
      .split(RegExp('[^a-zA-Z0-9]+'))
      .where((word) => word.isNotEmpty)
      .toList();
  if (words.isEmpty) return 'haptic';

  final buffer = StringBuffer(words.first.toLowerCase());
  for (final word in words.skip(1)) {
    buffer.write(word[0].toUpperCase());
    buffer.write(word.substring(1).toLowerCase());
  }
  var identifier = buffer.toString();
  if (RegExp('^[0-9]').hasMatch(identifier)) {
    identifier =
        'haptic${identifier[0].toUpperCase()}${identifier.substring(1)}';
  }
  return identifier;
}

/// Derives a `lower_case_with_underscores` Dart file name from a source
/// file name, e.g. `piano-loop.wav` → `piano_loop_haptic.dart`.
String dartFileNameFor(String filePath) {
  final words = p
      .basenameWithoutExtension(filePath)
      .split(RegExp('[^a-zA-Z0-9]+'))
      .where((word) => word.isNotEmpty)
      .map((word) => word.toLowerCase())
      .toList();
  if (words.isEmpty) return 'haptic.dart';
  var base = words.join('_');
  if (RegExp('^[0-9]').hasMatch(base)) {
    base = 'haptic_$base';
  }
  return '${base}_haptic.dart';
}

/// Generates a standalone Dart source file holding a haptic pattern as
/// constants: the AHAP document for iOS playback plus waveform arrays for
/// Android. The generated file has no dependencies.
String generateDartSource({
  required String identifier,
  required String sourceFileName,
  required String ahap,
  required AndroidWaveform waveform,
}) {
  final buffer = StringBuffer()
    ..writeln('// Generated by haptify from $sourceFileName.')
    ..writeln('// Regenerate with: haptify convert $sourceFileName')
    ..writeln()
    ..writeln('/// AHAP pattern for iOS Core Haptics playback,')
    ..writeln('/// e.g. `Gaimon.pattern(${identifier}Ahap)`.')
    ..writeln("const String ${identifier}Ahap = r'''")
    ..writeln(ahap)
    ..writeln("''';")
    ..writeln()
    ..writeln('/// Android waveform segment durations in milliseconds, for')
    ..writeln('/// `VibrationEffect.createWaveform` or the vibration plugin.')
    ..writeln('const List<int> ${identifier}Timings = ${waveform.timings};')
    ..writeln()
    ..writeln(
        '/// Android waveform amplitudes (0-255), aligned with the timings.')
    ..writeln(
        'const List<int> ${identifier}Amplitudes = ${waveform.amplitudes};')
    ..writeln()
    ..writeln('/// Android waveform repeat index (-1 plays once).')
    ..writeln('const int ${identifier}Repeat = ${waveform.repeatIndex};');
  return buffer.toString();
}
